/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet_ges_stock;

import BDS.Mycon;
import BDS.ResultSetTableModel;
import BDS.db_con;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author midek
 */
public class Produit extends javax.swing.JFrame {

    ResultSet rst;
    db_con db;
    public Produit() {
        db = new db_con(new Mycon().HOST_DB, new Mycon().USERNAME_DB, new Mycon().PASSWORD_DB, new Mycon().IPHOST, new Mycon().PORT);
        initComponents();
        table();
    }
    public void table() {
        String t[] = {"id","code_produit","reference","designation","prix","stock","stock_max"};
        rst = db.querySelect(t, "produit");
        table2.setModel(new ResultSetTableModel(rst));
    }
     void actualiser() {
        codeprod.setText("");
        ref.setText("");
        des.setText("");
        prix.setText("");
        stock.setText("");
        stock_max.setText("");
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        ajouter1 = new javax.swing.JButton();
        modifier1 = new javax.swing.JButton();
        supprimer1 = new javax.swing.JButton();
        actualiser = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        categorie1 = new javax.swing.JComboBox<>();
        rechercher1 = new javax.swing.JButton();
        rech = new javax.swing.JTextField();
        deconnexion1 = new javax.swing.JButton();
        exit1 = new javax.swing.JButton();
        stock = new javax.swing.JTextField();
        prix = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ref = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        des = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        codeprod = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        stock_max = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(875, 566));
        getContentPane().setLayout(null);

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "code_produit", "reference", "designation", "prix", "stock", "stock_max"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 830, 100);

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Produit");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 10, 300, 50);

        ajouter1.setBackground(new java.awt.Color(0, 0, 0));
        ajouter1.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        ajouter1.setForeground(new java.awt.Color(204, 204, 255));
        ajouter1.setText("Ajouter");
        ajouter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouter1ActionPerformed(evt);
            }
        });
        getContentPane().add(ajouter1);
        ajouter1.setBounds(10, 200, 120, 40);

        modifier1.setBackground(new java.awt.Color(0, 0, 0));
        modifier1.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        modifier1.setForeground(new java.awt.Color(204, 204, 255));
        modifier1.setText("modifier");
        modifier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifier1ActionPerformed(evt);
            }
        });
        getContentPane().add(modifier1);
        modifier1.setBounds(250, 200, 120, 40);

        supprimer1.setBackground(new java.awt.Color(0, 0, 0));
        supprimer1.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        supprimer1.setForeground(new java.awt.Color(204, 204, 255));
        supprimer1.setText("supprimer");
        supprimer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimer1ActionPerformed(evt);
            }
        });
        getContentPane().add(supprimer1);
        supprimer1.setBounds(490, 200, 120, 40);

        actualiser.setBackground(new java.awt.Color(0, 0, 0));
        actualiser.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        actualiser.setForeground(new java.awt.Color(204, 204, 255));
        actualiser.setText("actualiser");
        actualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualiserActionPerformed(evt);
            }
        });
        getContentPane().add(actualiser);
        actualiser.setBounds(710, 200, 120, 40);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setText("categorie");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(530, 280, 90, 30);

        categorie1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        categorie1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "code_produit", "reference", "designation", "prix", "stock", "stock_min" }));
        getContentPane().add(categorie1);
        categorie1.setBounds(610, 280, 180, 30);

        rechercher1.setBackground(new java.awt.Color(0, 0, 0));
        rechercher1.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        rechercher1.setForeground(new java.awt.Color(204, 204, 255));
        rechercher1.setText("rechercher");
        rechercher1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercher1ActionPerformed(evt);
            }
        });
        getContentPane().add(rechercher1);
        rechercher1.setBounds(490, 330, 130, 40);

        rech.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(rech);
        rech.setBounds(620, 330, 210, 40);

        deconnexion1.setBackground(new java.awt.Color(0, 0, 0));
        deconnexion1.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        deconnexion1.setForeground(new java.awt.Color(204, 204, 255));
        deconnexion1.setText("Deconnexion");
        deconnexion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deconnexion1ActionPerformed(evt);
            }
        });
        getContentPane().add(deconnexion1);
        deconnexion1.setBounds(30, 460, 150, 40);

        exit1.setBackground(new java.awt.Color(0, 0, 0));
        exit1.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        exit1.setForeground(new java.awt.Color(204, 204, 255));
        exit1.setText("Vente");
        exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit1ActionPerformed(evt);
            }
        });
        getContentPane().add(exit1);
        exit1.setBounds(700, 460, 120, 40);

        stock.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(stock);
        stock.setBounds(370, 280, 80, 30);

        prix.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(prix);
        prix.setBounds(100, 400, 90, 30);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        jLabel6.setText(" reference :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 320, 90, 30);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 255));
        jLabel7.setText("           prix :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 400, 90, 30);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 255));
        jLabel8.setText(" stock :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(310, 280, 60, 30);

        ref.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(ref);
        ref.setBounds(100, 320, 90, 30);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 255));
        jLabel9.setText("designation :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 360, 100, 30);

        des.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(des);
        des.setBounds(110, 360, 90, 30);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 255));
        jLabel10.setText("code_produit :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 280, 120, 30);

        codeprod.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(codeprod);
        codeprod.setBounds(130, 280, 80, 30);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("stock_max :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 350, 90, 30);

        stock_max.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(stock_max);
        stock_max.setBounds(370, 350, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/thumb-1920-541924.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1920, 1210));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 860, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajouter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouter1ActionPerformed
        if (codeprod.getText().equals("") || ref.getText().equals("") || des.getText().equals("") || prix.getText().equals("") || stock.getText().equals("") || stock_max.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "informations incomplete");
        } else {
            String[] colon = {"code_produit", "reference", "designation","prix","stock","stock_max"};
            String[] inf = {codeprod.getText(), ref.getText(),des.getText(),prix.getText(),stock.getText(),stock_max.getText()};
            System.out.println(db.queryInsert("produit", colon, inf));
            table();
            actualiser();
        }
    }//GEN-LAST:event_ajouter1ActionPerformed

    private void modifier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifier1ActionPerformed
      if (codeprod.getText().equals("") || ref.getText().equals("") || des.getText().equals("") || prix.getText().equals("") || stock.getText().equals("") || stock_max.getText().equals("")) {
            JOptionPane.showMessageDialog(this, " informations incomplete");
        } else {
                  String[] colon = {"code_produit","reference","designation","prix","stock","stock_max"};
              String[] inf = {codeprod.getText(), ref.getText(), des.getText(),prix.getText(),stock.getText(),stock_max.getText()};
            String id = String.valueOf(table2.getValueAt(table2.getSelectedRow(), 0));
            System.out.println(db.queryUpdate("produit", colon, inf, "id='" + id + "'"));
            table();
            actualiser();
        }
    }//GEN-LAST:event_modifier1ActionPerformed

    private void supprimer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimer1ActionPerformed
        String id = String.valueOf(table2.getValueAt(table2.getSelectedRow(), 0));
        if (JOptionPane.showConfirmDialog(this, "êtes vous sure de vouloir supprimer ", "attention!!!", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            db.queryDelete("produit", "id=" + id);
        } else {
            return;
        }
        table();
    }//GEN-LAST:event_supprimer1ActionPerformed

    private void actualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualiserActionPerformed
        actualiser();
        table();
    }//GEN-LAST:event_actualiserActionPerformed

    private void rechercher1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercher1ActionPerformed
        if (rech.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "entrer les données");
        } else {
           if (categorie1.getSelectedItem().equals("code_produit")) {
                rst = db.querySelectAll("produit", "code_produit LIKE '%" + rech.getText() + "%' ");
                table2.setModel(new ResultSetTableModel(rst));
            } else if (categorie1.getSelectedItem().equals("reference")) {
                rst = db.querySelectAll("produit", "reference LIKE '%" + rech.getText() + "%' ");
                table2.setModel(new ResultSetTableModel(rst));
            } else if (categorie1.getSelectedItem().equals("designation")) {
                rst = db.querySelectAll("produit", "deseignation LIKE '%" + rech.getText() + "%' ");
                table2.setModel(new ResultSetTableModel(rst));
            } else if (categorie1.getSelectedItem().equals("prix")) {
                rst = db.querySelectAll("produit", "prix LIKE '%" + rech.getText() + "%' ");
                table2.setModel(new ResultSetTableModel(rst));
            } else if (categorie1.getSelectedItem().equals("stock")) {
                rst = db.querySelectAll("produit", "stock LIKE '%" + rech.getText() + "%' ");
                table2.setModel(new ResultSetTableModel(rst));
            }else if (categorie1.getSelectedItem().equals("stock_max")) {
                rst = db.querySelectAll("produit", "stock LIKE '%" + rech.getText() + "%' ");
                table2.setModel(new ResultSetTableModel(rst));
            }
        }
    }//GEN-LAST:event_rechercher1ActionPerformed

    private void deconnexion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnexion1ActionPerformed
        int p= JOptionPane.showConfirmDialog(null, "Voulez vous quitter", "Quitter", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);

        if (p == JOptionPane.YES_OPTION) {
            dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_deconnexion1ActionPerformed

    private void exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit1ActionPerformed
        Vente v= new Vente();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exit1ActionPerformed

    private void table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MouseClicked
        codeprod.setText(String.valueOf(table2.getValueAt(table2.getSelectedRow(), 1)));
        ref.setText(String.valueOf(table2.getValueAt(table2.getSelectedRow(), 2)));
        des.setText(String.valueOf(table2.getValueAt(table2.getSelectedRow(), 3)));
prix.setText(String.valueOf(table2.getValueAt(table2.getSelectedRow(), 4)));
stock.setText(String.valueOf(table2.getValueAt(table2.getSelectedRow(), 5)));
stock_max.setText(String.valueOf(table2.getValueAt(table2.getSelectedRow(), 6)));

    }//GEN-LAST:event_table2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualiser;
    private javax.swing.JButton ajouter1;
    private javax.swing.JComboBox<String> categorie1;
    private javax.swing.JTextField codeprod;
    private javax.swing.JButton deconnexion1;
    private javax.swing.JTextField des;
    private javax.swing.JButton exit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modifier1;
    private javax.swing.JTextField prix;
    private javax.swing.JTextField rech;
    private javax.swing.JButton rechercher1;
    private javax.swing.JTextField ref;
    private javax.swing.JTextField stock;
    private javax.swing.JTextField stock_max;
    private javax.swing.JButton supprimer1;
    private javax.swing.JTable table2;
    // End of variables declaration//GEN-END:variables
}
